services:
  db:
    container_name: sae401_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: sae401
      MYSQL_DATABASE: sae401
      MYSQL_USER: sae401
      MYSQL_PASSWORD: sae401
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  phpmyadmin:
    container_name: sae401_myadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: sae401
      PMA_PASSWORD: sae401
    ports:
      - "81:80"
    depends_on:
      - db

volumes:
  mariadb_data: